# Multinomial AUC/PR AUC demo

In [2]:
import h2o
from h2o.estimators import H2OGradientBoostingEstimator
from h2o.utils.shared_utils import _locate # private function - used to find files within h2o git project directory

h2o.init(strict_version_check=False, port=54321)

Checking whether there is an H2O instance running at http://localhost:54321 . connected.

--------------------------  -----------------------------
H2O_cluster_uptime:         2 days 22 hours 37 mins
H2O_cluster_timezone:       Europe/Berlin
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.31.0.99999
H2O_cluster_version_age:    16 days
H2O_cluster_name:           mori
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    4.722 Gb
H2O_cluster_total_cores:    8
H2O_cluster_allowed_cores:  8
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://localhost:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
H2O_API_Extensions:         Algos, Core V3, Core V4
Python_version:             3.7.3 candidate
--------------------------  -----------------------------

In [3]:
cars = h2o.import_file(path=_locate("smalldata/junit/cars_20mpg.csv"))

features = ["displacement", "power", "weight", "acceleration", "year"]
response = "cylinders"
distribution = "multinomial"

cars[response] = cars[response].asfactor()

r = cars[0].runif()
train = cars[r > .3]
valid = cars[r <= .3]
    
# train model
gbm = H2OGradientBoostingEstimator(distribution="multinomial", 
                                   ntrees=100, 
                                   max_depth=3, 
                                   learn_rate=0.01)
gbm.train(x               =features, 
          y               =response, 
          training_frame  =train,
          validation_frame=valid)
gbm.show()

Parse progress: |█████████████████████████████████████████████████████████| 100%
gbm Model Build progress: |███████████████████████████████████████████████| 100%
Model Details
=============
H2OGradientBoostingEstimator :  Gradient Boosting Machine
Model Key:  GBM_model_python_1603462757331_111


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,100.0,500.0,67783.0,1.0,3.0,2.994,2.0,7.0,6.14

ModelMetricsMultinomial: gbm
** Reported on train data. **

MSE: 0.07730179689097179
RMSE: 0.2780320069541847
LogLoss: 0.3179837213795853
Mean Per-Class Error: 0.40714285714285714
AUC: 0.9994916665386384
AUCPR: 0.9976172889213937

Multinomial AUC values:

             type first_class_domain second_class_domain       auc
0       3 vs Rest                  3                None  1.000000
1       4 vs Rest                  4                None  0.999343
2       5 vs Rest                  5                None  0.994233
3       6 vs Rest                  6                None  0.999395
4       8 vs Rest                  8                None  0.999941
5       Macro OVR               None                None  0.998582
6    Weighted OVR               None                None  0.999492
7   Class 3 vs. 4                  3                   4  0.997763
8   Class 3 vs. 5                  3                   5  1.000000
9   Class 3 vs. 6                  3                   6  1.000000
10  Class 3 vs. 8                  3                   8  1.000000
11  Class 4 vs. 5                  4                   5  0.983221
12  Class 4 vs. 6                  4                   6  0.999700
13  Class 4 vs. 8                  4                   8  1.000000
14  Class 5 vs. 6                  5                   6  0.988095
15  Class 5 vs. 8                  5                   8  0.997942
16  Class 6 vs. 8                  6                   8  0.999890
17      Macro OVO               None                None  0.996661
18   Weighted OVO               None                None  0.996721

Multinomial auc_pr values:

             type first_class_domain second_class_domain    auc_pr
0       3 vs Rest                  3                None  1.000000
1       4 vs Rest                  4                None  0.999371
2       5 vs Rest                  5                None  0.777448
3       6 vs Rest                  6                None  0.997491
4       8 vs Rest                  8                None  0.999849
5       Macro OVR               None                None  0.954832
6    Weighted OVR               None                None  0.997617
7   Class 3 vs. 4                  3                   4  0.999955
8   Class 3 vs. 5                  3                   5  1.000000
9   Class 3 vs. 6                  3                   6  1.000000
10  Class 3 vs. 8                  3                   8  1.000000
11  Class 4 vs. 5                  4                   5  0.896983
12  Class 4 vs. 6                  4                   6  0.999351
13  Class 4 vs. 8                  4                   8  1.000000
14  Class 5 vs. 6                  5                   6  0.999350
15  Class 5 vs. 8                  5                   8  0.952053
16  Class 6 vs. 8                  6                   8  0.999924
17      Macro OVO               None                None  0.984762
18   Weighted OVO               None                None  0.983043

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class

     3      4    5     6     8     Error     Rate
0  0.0    3.0  0.0   0.0   0.0  1.000000    3 / 3
1  0.0  149.0  0.0   0.0   0.0  0.000000  0 / 149
2  0.0    2.0  0.0   1.0   0.0  1.000000    3 / 3
3  0.0    1.0  0.0  54.0   1.0  0.035714   2 / 56
4  0.0    0.0  0.0   0.0  81.0  0.000000   0 / 81
5  0.0  155.0  0.0  55.0  82.0  0.027397  8 / 292

Top-5 Hit Ratios:

   k  hit_ratio
0  1   0.972603
1  2   1.000000
2  3   1.000000
3  4   1.000000
4  5   1.000000

ModelMetricsMultinomial: gbm
** Reported on validation data. **

MSE: 0.08557559800431094
RMSE: 0.2925330716420127
LogLoss: 0.33970917864435185
Mean Per-Class Error: 0.21773399014778322
AUC: 0.9958408546018811
AUCPR: 0.9944076951783811

Multinomial AUC values:

             type first_class_domain second_class_domain       auc
0       3 vs Rest                  3                None  1.000000
1       4 vs Rest                  4                None  0.993227
2       5 vs Rest                  5                None  0.000000
3       6 vs Rest                  6                None  0.997093
4       8 vs Rest                  8                None  1.000000
5       Macro OVR               None                None  0.798064
6    Weighted OVR               None                None  0.995841
7   Class 3 vs. 4                  3                   4  0.991379
8   Class 3 vs. 5                  3                   5  0.500000
9   Class 3 vs. 6                  3                   6  1.000000
10  Class 3 vs. 8                  3                   8  1.000000
11  Class 4 vs. 5                  4                   5  0.500000
12  Class 4 vs. 6                  4                   6  0.991379
13  Class 4 vs. 8                  4                   8  1.000000
14  Class 5 vs. 6                  5                   6  0.500000
15  Class 5 vs. 8                  5                   8  0.500000
16  Class 6 vs. 8                  6                   8  1.000000
17      Macro OVO               None                None  0.798276
18   Weighted OVO               None                None  0.871734

Multinomial auc_pr values:

             type first_class_domain second_class_domain    auc_pr
0       3 vs Rest                  3                None  1.000000
1       4 vs Rest                  4                None  0.992835
2       5 vs Rest                  5                None  0.000000
3       6 vs Rest                  6                None  0.991832
4       8 vs Rest                  8                None  1.000000
5       Macro OVR               None                None  0.796934
6    Weighted OVR               None                None  0.994408
7   Class 3 vs. 4                  3                   4  0.999853
8   Class 3 vs. 5                  3                   5  0.500000
9   Class 3 vs. 6                  3                   6  1.000000
10  Class 3 vs. 8                  3                   8  1.000000
11  Class 4 vs. 5                  4                   5  0.500000
12  Class 4 vs. 6                  4                   6  0.992467
13  Class 4 vs. 8                  4                   8  1.000000
14  Class 5 vs. 6                  5                   6  0.500000
15  Class 5 vs. 8                  5                   8  0.500000
16  Class 6 vs. 8                  6                   8  1.000000
17      Macro OVO               None                None  0.799232
18   Weighted OVO               None                None  0.873036

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class

     3     4    5     6     8     Error     Rate
0  0.0   1.0  0.0   0.0   0.0  1.000000    1 / 1
1  0.0  57.0  0.0   1.0   0.0  0.017241   1 / 58
2  0.0   0.0  0.0   0.0   0.0       NaN    0 / 0
3  0.0   2.0  0.0  26.0   0.0  0.071429   2 / 28
4  0.0   0.0  0.0   0.0  27.0  0.000000   0 / 27
5  0.0  60.0  0.0  27.0  27.0  0.035088  4 / 114

Top-5 Hit Ratios:

   k  hit_ratio
0  1   0.964912
1  2   1.000000
2  3   1.000000
3  4   1.000000
4  5   1.000000

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_logloss,training_classification_error,training_auc,training_pr_auc,validation_rmse,validation_logloss,validation_classification_error,validation_auc,validation_pr_auc
0,,2020-10-26 13:57:00,0.002 sec,0.0,0.800000,1.609438,0.636986,0.500000,0.374320,0.800000,1.609438,0.649123,0.500000,0.375346
1,,2020-10-26 13:57:00,0.010 sec,1.0,0.792415,1.572234,0.030822,0.998277,0.994645,0.792590,1.573083,0.035088,0.994820,0.992039
2,,2020-10-26 13:57:00,0.012 sec,2.0,0.784855,1.536514,0.030822,0.998593,0.996399,0.785234,1.538301,0.035088,0.992308,0.988887
3,,2020-10-26 13:57:00,0.014 sec,3.0,0.777331,1.502218,0.030822,0.998549,0.996423,0.777886,1.504762,0.035088,0.993841,0.990904
4,,2020-10-26 13:57:00,0.016 sec,4.0,0.769833,1.469201,0.030822,0.998573,0.996448,0.770596,1.472607,0.035088,0.992308,0.988887
5,,2020-10-26 13:57:00,0.018 sec,5.0,0.762375,1.437429,0.030822,0.998549,0.996423,0.763318,1.441527,0.035088,0.993810,0.990903
6,,2020-10-26 13:57:00,0.021 sec,6.0,0.754945,1.406773,0.030822,0.998624,0.995812,0.756080,1.411573,0.035088,0.993080,0.989864
7,,2020-10-26 13:57:00,0.024 sec,7.0,0.747556,1.377210,0.030822,0.998696,0.995876,0.748855,1.382557,0.035088,0.993810,0.990899
8,,2020-10-26 13:57:00,0.026 sec,8.0,0.740198,1.348630,0.030822,0.998744,0.995925,0.741689,1.354617,0.035088,0.993372,0.990316
9,,2020-10-26 13:57:00,0.028 sec,9.0,0.732882,1.321018,0.030822,0.998720,0.995899,0.734540,1.327504,0.035088,0.994199,0.991512
10,,2020-10-26 13:57:00,0.031 sec,10.0,0.725599,1.294279,0.030822,0.998744,0.995925,0.727451,1.301354,0.035088,0.993567,0.990648
11,,2020-10-26 13:57:00,0.034 sec,11.0,0.718360,1.268404,0.030822,0.998720,0.995899,0.720399,1.276027,0.035088,0.993567,0.990648
12,,2020-10-26 13:57:00,0.037 sec,12.0,0.711145,1.243255,0.030822,0.998859,0.996148,0.713358,1.251326,0.035088,0.994078,0.991442
13,,2020-10-26 13:57:00,0.040 sec,13.0,0.703979,1.218906,0.030822,0.998883,0.996172,0.706436,1.227661,0.035088,0.994078,0.991442
14,,2020-10-26 13:57:00,0.043 sec,14.0,0.696846,1.195244,0.030822,0.998955,0.996241,0.699449,1.204313,0.035088,0.994078,0.991442
15,,2020-10-26 13:57:00,0.049 sec,15.0,0.689769,1.172330,0.030822,0.998955,0.996241,0.692605,1.182014,0.035088,0.994078,0.991442
16,,2020-10-26 13:57:00,0.055 sec,16.0,0.682721,1.150011,0.030822,0.998969,0.996288,0.685701,1.159976,0.035088,0.994078,0.991442
17,,2020-10-26 13:57:00,0.058 sec,17.0,0.675716,1.128319,0.030822,0.998984,0.996336,0.678846,1.138568,0.035088,0.994175,0.991610
18,,2020-10-26 13:57:00,0.061 sec,18.0,0.668775,1.107288,0.030822,0.999118,0.996508,0.672154,1.118131,0.035088,0.994175,0.991610
19,,2020-10-26 13:57:00,0.063 sec,19.0,0.661871,1.086805,0.030822,0.999032,0.996381,0.665465,1.098136,0.035088,0.994078,0.991442

See the whole table with table.as_data_frame()

Variable Importances:

       variable  relative_importance  scaled_importance  percentage
0  displacement          6498.680176           1.000000    0.976815
1  acceleration            65.170708           0.010028    0.009796
2         power            48.231422           0.007422    0.007250
3          year            24.272539           0.003735    0.003648
4        weight            16.576046           0.002551    0.002492

In [4]:
gbm.auc()

0.9994916665386384

In [5]:
gbm.aucpr()

0.9976172889213937

In [6]:
gbm.multinomial_auc_table()

Multinomial AUC values:

             type first_class_domain second_class_domain       auc
0       3 vs Rest                  3                None  1.000000
1       4 vs Rest                  4                None  0.999343
2       5 vs Rest                  5                None  0.994233
3       6 vs Rest                  6                None  0.999395
4       8 vs Rest                  8                None  0.999941
5       Macro OVR               None                None  0.998582
6    Weighted OVR               None                None  0.999492
7   Class 3 vs. 4                  3                   4  0.997763
8   Class 3 vs. 5                  3                   5  1.000000
9   Class 3 vs. 6                  3                   6  1.000000
10  Class 3 vs. 8                  3                   8  1.000000
11  Class 4 vs. 5                  4                   5  0.983221
12  Class 4 vs. 6                  4                   6  0.999700
13  Class 4 vs. 8                  4                   8  1.000000
14  Class 5 vs. 6                  5                   6  0.988095
15  Class 5 vs. 8                  5                   8  0.997942
16  Class 6 vs. 8                  6                   8  0.999890
17      Macro OVO               None                None  0.996661
18   Weighted OVO               None                None  0.996721

In [7]:
# train model with AUC/PR AUC type
gbm = H2OGradientBoostingEstimator(distribution="multinomial", 
                                   ntrees=100, 
                                   max_depth=3, 
                                   learn_rate=0.01,
                                   multinomial_auc_type='MACRO_OVR')
gbm.train(x               =features, 
          y               =response, 
          training_frame  =train,
          validation_frame=valid)
print(gbm.auc())
print(gbm.multinomial_auc_table()[3][5]) # Macro OVR line

gbm Model Build progress: |███████████████████████████████████████████████| 100%
0.9985824178098481
0.9985824178098481

In [8]:
# early stopping

gbm = H2OGradientBoostingEstimator(distribution="multinomial", 
                                   ntrees=100, 
                                   max_depth=3, 
                                   learn_rate=0.01,
                                   stopping_metric="AUCPR", 
                                   stopping_tolerance=0.01, 
                                   stopping_rounds=3)
gbm.train(x               =features, 
          y               =response, 
          training_frame  =train,
          validation_frame=valid)
gbm.scoring_history()

gbm Model Build progress: |███████████████████████████████████████████████| 100%

,,timestamp,duration,number_of_trees,training_rmse,training_logloss,training_classification_error,training_auc,training_pr_auc,validation_rmse,validation_logloss,validation_classification_error,validation_auc,validation_pr_auc
0,,2020-10-26 13:57:02,0.002 sec,0.0,0.800000,1.609438,0.636986,0.500000,0.374320,0.800000,1.609438,0.649123,0.500000,0.375346
1,,2020-10-26 13:57:02,0.012 sec,1.0,0.792415,1.572234,0.030822,0.998277,0.994645,0.792590,1.573083,0.035088,0.994820,0.992039
2,,2020-10-26 13:57:02,0.015 sec,2.0,0.784855,1.536514,0.030822,0.998593,0.996399,0.785234,1.538301,0.035088,0.992308,0.988887
3,,2020-10-26 13:57:02,0.019 sec,3.0,0.777331,1.502218,0.030822,0.998549,0.996423,0.777886,1.504762,0.035088,0.993841,0.990904
4,,2020-10-26 13:57:02,0.023 sec,4.0,0.769833,1.469201,0.030822,0.998573,0.996448,0.770596,1.472607,0.035088,0.992308,0.988887
5,,2020-10-26 13:57:02,0.028 sec,5.0,0.762375,1.437429,0.030822,0.998549,0.996423,0.763318,1.441527,0.035088,0.993810,0.990903
6,,2020-10-26 13:57:02,0.032 sec,6.0,0.754945,1.406773,0.030822,0.998624,0.995812,0.756080,1.411573,0.035088,0.993080,0.989864

In [9]:
# grid search

from h2o.grid.grid_search import H2OGridSearch
hyper_parameters = {'ntrees': [5, 10], 'max_depth': [10, 20]}
gs = H2OGridSearch(H2OGradientBoostingEstimator(distribution = "multinomial"), hyper_parameters)
gs.train(x=features, y=response, training_frame=train)
gs.auc(train=True)

gbm Grid Build progress: |████████████████████████████████████████████████| 100%

{'Grid_GBM_py_3_sid_b17b_model_python_1603462757331_114_model_4': 0.9995156185181562,
 'Grid_GBM_py_3_sid_b17b_model_python_1603462757331_114_model_3': 0.9995156185181562,
 'Grid_GBM_py_3_sid_b17b_model_python_1603462757331_114_model_1': 0.9991707922989619,
 'Grid_GBM_py_3_sid_b17b_model_python_1603462757331_114_model_2': 0.9991707922989619}

In [10]:
# domain is too big

air = h2o.import_file(path=_locate("smalldata/airlines/AirlinesTrain.csv.zip"))

features = ["Origin", "Dest", "IsDepDelayed", "UniqueCarrier", "fMonth", "fDayofMonth", "fDayOfWeek"]
response = "Dest"

r = air[0].runif()
train = air[r < 0.8]
valid = air[r >= 0.8]

#Too many domains - AUC/PR AUC is not calculated
gbm = H2OGradientBoostingEstimator(distribution="multinomial", 
                                   ntrees=100, 
                                   max_depth=3, 
                                   learn_rate=0.01)
gbm.train(x               =features, 
          y               =response, 
          training_frame  =train,
          validation_frame=valid)
gbm.show()

Parse progress: |█████████████████████████████████████████████████████████| 100%
gbm Model Build progress: |███████████████████████████████████████████████| 100%
Model Details
=============
H2OGradientBoostingEstimator :  Gradient Boosting Machine
Model Key:  GBM_model_python_1603462757331_115


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,100.0,9800.0,2004702.0,1.0,3.0,2.99949,2.0,8.0,7.792959

ModelMetricsMultinomial: gbm
** Reported on train data. **

MSE: 0.43256210340338636
RMSE: 0.657694536546706
LogLoss: 1.3808885688343495
Mean Per-Class Error: 0.7692195670872881
AUC: NaN
AUCPR: NaN
Multinomial auc values: Table is not computed due to domain size.
Multinomial auc_pr values: Table is not computed due to domain size.

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class

,ABE,ABQ,ACY,ALB,ATL,AVP,BDL,BGM,BNA,BOS,...,SNA,STL,SWF,SYR,TOL,TPA,TUS,UCA,Error,Rate
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,106 / 106
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,77 / 77
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,19 / 19
3,0.0,0.0,0.0,21.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.743902,61 / 82
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,19 / 19
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,25 / 25
6,0.0,0.0,0.0,6.0,0.0,0.0,15.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.772727,51 / 66
7,0.0,0.0,0.0,0.0,0.0,0.0,11.0,7.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.840909,37 / 44
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,41 / 41
9,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,131.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.636111,229 / 360
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.939394,31 / 33
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,43.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.852941,87 / 102
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,13.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.643875,226 / 351
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.677215,214 / 316
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,21 / 21
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,19 / 19
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.666667,2 / 3
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0 / 16
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,41 / 41
19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.424051,67 / 158

See the whole table with table.as_data_frame()

Top-10 Hit Ratios:

    k  hit_ratio
0   1   0.645621
1   2   0.772611
2   3   0.832840
3   4   0.872856
4   5   0.900470
5   6   0.918334
6   7   0.930839
7   8   0.940384
8   9   0.948295
9  10   0.954828

ModelMetricsMultinomial: gbm
** Reported on validation data. **

MSE: 0.44872082618688997
RMSE: 0.669866274854086
LogLoss: 1.5610352969172685
Mean Per-Class Error: 0.7779080059439285
AUC: NaN
AUCPR: NaN
Multinomial auc values: Table is not computed due to domain size.
Multinomial auc_pr values: Table is not computed due to domain size.

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class

,ABE,ABQ,ACY,ALB,ATL,AVP,BDL,BGM,BNA,BOS,...,SNA,STL,SWF,SYR,TOL,TPA,TUS,UCA,Error,Rate
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,24 / 24
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,20 / 20
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0 / 0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.937500,15 / 16
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,4 / 4
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,2 / 2
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,15 / 15
7,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,9 / 9
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,8 / 8
9,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,22.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.734940,61 / 83
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,4 / 4
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.840000,21 / 25
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.689189,51 / 74
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.675325,52 / 77
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,3 / 3
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,6 / 6
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0 / 0
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0 / 3
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,11 / 11
19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.280000,7 / 25

See the whole table with table.as_data_frame()

Top-10 Hit Ratios:

    k  hit_ratio
0   1   0.622075
1   2   0.740940
2   3   0.783599
3   4   0.816732
4   5   0.848830
5   6   0.868503
6   7   0.881549
7   8   0.896252
8   9   0.906813
9  10   0.913647

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_logloss,training_classification_error,training_auc,training_pr_auc,validation_rmse,validation_logloss,validation_classification_error,validation_auc,validation_pr_auc
0,,2020-10-26 13:57:03,0.006 sec,0.0,0.989796,4.584967,0.865762,NaN,NaN,0.989796,4.584967,0.868710,NaN,NaN
1,,2020-10-26 13:57:03,0.522 sec,1.0,0.981696,4.070755,0.365915,NaN,NaN,0.981840,4.081009,0.375854,NaN,NaN
2,,2020-10-26 13:57:04,1.128 sec,2.0,0.975470,3.828411,0.365455,NaN,NaN,0.975723,3.844904,0.375647,NaN,NaN
3,,2020-10-26 13:57:04,1.406 sec,3.0,0.969602,3.651841,0.365557,NaN,NaN,0.969961,3.673661,0.375233,NaN,NaN
4,,2020-10-26 13:57:05,1.660 sec,4.0,0.963919,3.510224,0.365557,NaN,NaN,0.964385,3.536805,0.375233,NaN,NaN
5,,2020-10-26 13:57:05,1.919 sec,5.0,0.958359,3.391067,0.365506,NaN,NaN,0.958929,3.421872,0.375026,NaN,NaN
6,,2020-10-26 13:57:05,2.188 sec,6.0,0.952904,3.288194,0.365506,NaN,NaN,0.953582,3.323070,0.375026,NaN,NaN
7,,2020-10-26 13:57:05,2.455 sec,7.0,0.947534,3.197493,0.365251,NaN,NaN,0.948320,3.236092,0.375026,NaN,NaN
8,,2020-10-26 13:57:06,2.744 sec,8.0,0.942231,3.116047,0.365200,NaN,NaN,0.943128,3.158202,0.375026,NaN,NaN
9,,2020-10-26 13:57:06,3.107 sec,9.0,0.936996,3.042239,0.365149,NaN,NaN,0.938003,3.087654,0.375026,NaN,NaN
10,,2020-10-26 13:57:06,3.390 sec,10.0,0.931801,2.974148,0.364945,NaN,NaN,0.932913,3.022502,0.375647,NaN,NaN
11,,2020-10-26 13:57:07,3.641 sec,11.0,0.926658,2.911369,0.364281,NaN,NaN,0.927881,2.962628,0.376890,NaN,NaN
12,,2020-10-26 13:57:07,3.891 sec,12.0,0.921575,2.853238,0.364281,NaN,NaN,0.922906,2.907256,0.376475,NaN,NaN
13,,2020-10-26 13:57:11,7.906 sec,41.0,0.795201,1.967114,0.359994,NaN,NaN,0.799753,2.076648,0.377511,NaN,NaN
14,,2020-10-26 13:57:22,18.930 sec,100.0,0.657695,1.380889,0.354379,NaN,NaN,0.669866,1.561035,0.377925,NaN,NaN

Variable Importances:

        variable  relative_importance  scaled_importance  percentage
0         Origin        154708.312500           1.000000    0.501400
1  UniqueCarrier        145778.015625           0.942277    0.472457
2    fDayofMonth          3975.156738           0.025695    0.012883
3         fMonth          2744.356201           0.017739    0.008894
4   IsDepDelayed          1051.548462           0.006797    0.003408
5     fDayOfWeek           295.376495           0.001909    0.000957

In [11]:
gbm.multinomial_auc_table()

'Table is not computed due to domain size.'